version: "3.7"
services:
  n8n-server:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    volumes:
      - ./.n8n:/root/.n8n
    ports:
      - "5678:5678"
    env_file:
      - ./.env